export default function languages() {
    return [
        { "label": "Abkhaz (аҧсуа бызшәа, аҧсшәа)", "value": "ab" },
        { "label": "Afar (Afaraf)", "value": "aa" },
        { "label": "Afrikaans (Afrikaans)", "value": "af" },
        { "label": "Akan (Akan)", "value": "ak" },
        { "label": "Albanian (Shqip)", "value": "sq" },
        { "label": "Amharic (አማርኛ)", "value": "am" },
        { "label": "Arabic (العربية)", "value": "ar" },
        { "label": "Aragonese (aragonés)", "value": "an" },
        { "label": "Armenian (Հայերեն)", "value": "hy" },
        { "label": "Assamese (অসমীয়া)", "value": "as" },
        { "label": "Avaric (авар мацӀ, магӀарул мацӀ)", "value": "av" },
        { "label": "Avestan (avesta)", "value": "ae" },
        { "label": "Aymara (aymar aru)", "value": "ay" },
        { "label": "Azerbaijani (azərbaycan dili)", "value": "az" },
        { "label": "Bambara (bamanankan)", "value": "bm" },
        { "label": "Bashkir (башҡорт теле)", "value": "ba" },
        { "label": "Basque (euskara, euskera)", "value": "eu" },
        { "label": "Belarusian (беларуская мова)", "value": "be" },
        { "label": "Bengali, Bangla (বাংলা)", "value": "bn" },
        { "label": "Bihari (भोजपुरी)", "value": "bh" },
        { "label": "Bislama (Bislama)", "value": "bi" },
        { "label": "Bosnian (bosanski jezik)", "value": "bs" },
        { "label": "Breton (brezhoneg)", "value": "br" },
        { "label": "Bulgarian (български език)", "value": "bg" },
        { "label": "Burmese (ဗမာစာ)", "value": "my" },
        { "label": "Catalan (català)", "value": "ca" },
        { "label": "Chamorro (Chamoru)", "value": "ch" },
        { "label": "Chechen (нохчийн мотт)", "value": "ce" },
        { "label": "Chichewa, Chewa, Nyanja (chiCheŵa, chinyanja)", "value": "ny" },
        { "label": "Chinese (中文 (Zhōngwén), 汉语, 漢語)", "value": "zh" },
        { "label": "Chuvash (чӑваш чӗлхи)", "value": "cv" },
        { "label": "Cornish (Kernewek)", "value": "kw" },
        { "label": "Corsican (corsu, lingua corsa)", "value": "co" },
        { "label": "Cree (ᓀᐦᐃᔭᐍᐏᐣ)", "value": "cr" },
        { "label": "Croatian (hrvatski jezik)", "value": "hr" },
        { "label": "Czech (čeština, český jazyk)", "value": "cs" },
        { "label": "Danish (dansk)", "value": "da" },
        { "label": "Divehi, Dhivehi, Maldivian (ދިވެހި)", "value": "dv" },
        { "label": "Dutch (Nederlands, Vlaams)", "value": "nl" },
        { "label": "Dzongkha (རྫོང་ཁ)", "value": "dz" },
        { "label": "English (English)", "value": "en" },
        { "label": "Esperanto (Esperanto)", "value": "eo" },
        { "label": "Estonian (eesti, eesti keel)", "value": "et" },
        { "label": "Ewe (Eʋegbe)", "value": "ee" },
        { "label": "Faroese (føroyskt)", "value": "fo" },
        { "label": "Fijian (vosa Vakaviti)", "value": "fj" },
        { "label": "Finnish (suomi, suomen kieli)", "value": "fi" },
        { "label": "French (français, langue française)", "value": "fr" },
        { "label": "Fula, Fulah, Pulaar, Pular (Fulfulde, Pulaar, Pular)", "value": "ff" },
        { "label": "Galician (galego)", "value": "gl" },
        { "label": "Georgian (ქართული)", "value": "ka" },
        { "label": "German (Deutsch)", "value": "de" },
        { "label": "Greek (modern) (ελληνικά)", "value": "el" },
        { "label": "Guaraní (Avañe'ẽ)", "value": "gn" },
        { "label": "Gujarati (ગુજરાતી)", "value": "gu" },
        { "label": "Haitian, Haitian Creole (Kreyòl ayisyen)", "value": "ht" },
        { "label": "Hausa ((Hausa) هَوُسَ)", "value": "ha" },
        { "label": "Hebrew (modern) (עברית)", "value": "he" },
        { "label": "Herero (Otjiherero)", "value": "hz" },
        { "label": "Hindi (हिन्दी, हिंदी)", "value": "hi" },
        { "label": "Hiri Motu (Hiri Motu)", "value": "ho" },
        { "label": "Hungarian (magyar)", "value": "hu" },
        { "label": "Interlingua (Interlingua)", "value": "ia" },
        { "label": "Indonesian (Bahasa Indonesia)", "value": "id" },
        { "label": "Interlingue (Originally called Occidental; then Interlingue after WWII)", "value": "ie" },
        { "label": "Irish (Gaeilge)", "value": "ga" },
        { "label": "Igbo (Asụsụ Igbo)", "value": "ig" },
        { "label": "Inupiaq (Iñupiaq, Iñupiatun)", "value": "ik" },
        { "label": "Ido (Ido)", "value": "io" },
        { "label": "Icelandic (Íslenska)", "value": "is" },
        { "label": "Italian (Italiano)", "value": "it" },
        { "label": "Inuktitut (ᐃᓄᒃᑎᑐᑦ)", "value": "iu" },
        { "label": "Japanese (日本語 (にほんご))", "value": "ja" },
        { "label": "Javanese (ꦧꦱꦗꦮ, Basa Jawa)", "value": "jv" },
        { "label": "Kalaallisut, Greenlandic (kalaallisut, kalaallit oqaasii)", "value": "kl" },
        { "label": "Kannada (ಕನ್ನಡ)", "value": "kn" },
        { "label": "Kanuri (Kanuri)", "value": "kr" },
        { "label": "Kashmiri (कश्मीरी, كشميري‎)", "value": "ks" },
        { "label": "Kazakh (қазақ тілі)", "value": "kk" },
        { "label": "Khmer (ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ)", "value": "km" },
        { "label": "Kikuyu, Gikuyu (Gĩkũyũ)", "value": "ki" },
        { "label": "Kinyarwanda (Ikinyarwanda)", "value": "rw" },
        { "label": "Kyrgyz (Кыргызча, Кыргыз тили)", "value": "ky" },
        { "label": "Komi (коми кыв)", "value": "kv" },
        { "label": "Kongo (Kikongo)", "value": "kg" },
        { "label": "Korean (한국어)", "value": "ko" },
        { "label": "Kurdish (Kurdî, كوردی‎)", "value": "ku" },
        { "label": "Kwanyama, Kuanyama (Kuanyama)", "value": "kj" },
        { "label": "Latin (latine, lingua latina)", "value": "la" },
        { "label": "Luxembourgish, Letzeburgesch (Lëtzebuergesch)", "value": "lb" },
        { "label": "Ganda (Luganda)", "value": "lg" },
        { "label": "Limburgish, Limburgan, Limburger (Limburgs)", "value": "li" },
        { "label": "Lingala (Lingála)", "value": "ln" },
        { "label": "Lao (ພາສາລາວ)", "value": "lo" },
        { "label": "Lithuanian (lietuvių kalba)", "value": "lt" },
        { "label": "Luba-Katanga (Tshiluba)", "value": "lu" },
        { "label": "Latvian (latviešu valoda)", "value": "lv" },
        { "label": "Manx (Gaelg, Gailck)", "value": "gv" },
        { "label": "Macedonian (македонски јазик)", "value": "mk" },
        { "label": "Malagasy (fiteny malagasy)", "value": "mg" },
        { "label": "Malay (bahasa Melayu, بهاس ملايو‎)", "value": "ms" },
        { "label": "Malayalam (മലയാളം)", "value": "ml" },
        { "label": "Maltese (Malti)", "value": "mt" },
        { "label": "Māori (te reo Māori)", "value": "mi" },
        { "label": "Marathi (Marāṭhī) (मराठी)", "value": "mr" },
        { "label": "Marshallese (Kajin M̧ajeļ)", "value": "mh" },
        { "label": "Mongolian (Монгол хэл)", "value": "mn" },
        { "label": "Nauruan (Dorerin Naoero)", "value": "na" },
        { "label": "Navajo, Navaho (Diné bizaad)", "value": "nv" },
        { "label": "Northern Ndebele (isiNdebele)", "value": "nd" },
        { "label": "Nepali (नेपाली)", "value": "ne" },
        { "label": "Ndonga (Owambo)", "value": "ng" },
        { "label": "Norwegian Bokmål (Norsk bokmål)", "value": "nb" },
        { "label": "Norwegian Nynorsk (Norsk nynorsk)", "value": "nn" },
        { "label": "Norwegian (Norsk)", "value": "no" },
        { "label": "Nuosu (ꆈꌠ꒿ Nuosuhxop)", "value": "ii" },
        { "label": "Southern Ndebele (isiNdebele)", "value": "nr" },
        { "label": "Occitan (occitan, lenga d'òc)", "value": "oc" },
        { "label": "Ojibwe, Ojibwa (ᐊᓂᔑᓈᐯᒧᐎᓐ)", "value": "oj" },
        { "label": "Old Church Slavonic, Church Slavonic, Old Bulgarian (ѩзыкъ словѣньскъ)", "value": "cu" },
        { "label": "Oromo (Afaan Oromoo)", "value": "om" },
        { "label": "Oriya (ଓଡ଼ିଆ)", "value": "or" },
        { "label": "Ossetian, Ossetic (ирон æвзаг)", "value": "os" },
        { "label": "(Eastern) Punjabi (ਪੰਜਾਬੀ)", "value": "pa" },
        { "label": "Pāli (पाऴि)", "value": "pi" },
        { "label": "Persian (Farsi) (فارسی)", "value": "fa" },
        { "label": "Polish (język polski, polszczyzna)", "value": "pl" },
        { "label": "Pashto, Pushto (پښتو)", "value": "ps" },
        { "label": "Portuguese (Português)", "value": "pt" },
        { "label": "Quechua (Runa Simi, Kichwa)", "value": "qu" },
        { "label": "Romansh (rumantsch grischun)", "value": "rm" },
        { "label": "Kirundi (Ikirundi)", "value": "rn" },
        { "label": "Romanian (Română)", "value": "ro" },
        { "label": "Russian (Русский)", "value": "ru" },
        { "label": "Sanskrit (Saṁskṛta) (संस्कृतम्)", "value": "sa" },
        { "label": "Sardinian (sardu)", "value": "sc" },
        { "label": "Sindhi (सिन्धी, سنڌي، سندھی‎)", "value": "sd" },
        { "label": "Northern Sami (Davvisámegiella)", "value": "se" },
        { "label": "Samoan (gagana fa'a Samoa)", "value": "sm" },
        { "label": "Sango (yângâ tî sängö)", "value": "sg" },
        { "label": "Serbian (српски језик)", "value": "sr" },
        { "label": "Scottish Gaelic, Gaelic (Gàidhlig)", "value": "gd" },
        { "label": "Shona (chiShona)", "value": "sn" },
        { "label": "Sinhalese, Sinhala (සිංහල)", "value": "si" },
        { "label": "Slovak (slovenčina, slovenský jazyk)", "value": "sk" },
        { "label": "Slovene (slovenski jezik, slovenščina)", "value": "sl" },
        { "label": "Somali (Soomaaliga, af Soomaali)", "value": "so" },
        { "label": "Southern Sotho (Sesotho)", "value": "st" },
        { "label": "Spanish (Español)", "value": "es" },
        { "label": "Sundanese (Basa Sunda)", "value": "su" },
        { "label": "Swahili (Kiswahili)", "value": "sw" },
        { "label": "Swati (SiSwati)", "value": "ss" },
        { "label": "Swedish (svenska)", "value": "sv" },
        { "label": "Tamil (தமிழ்)", "value": "ta" },
        { "label": "Telugu (తెలుగు)", "value": "te" },
        { "label": "Tajik (тоҷикӣ, toçikī, تاجیکی‎)", "value": "tg" },
        { "label": "Thai (ไทย)", "value": "th" },
        { "label": "Tigrinya (ትግርኛ)", "value": "ti" },
        { "label": "Tibetan Standard, Tibetan, Central (བོད་ཡིག)", "value": "bo" },
        { "label": "Turkmen (Türkmen, Түркмен)", "value": "tk" },
        { "label": "Tagalog (Wikang Tagalog)", "value": "tl" },
        { "label": "Tswana (Setswana)", "value": "tn" },
        { "label": "Tonga (Tonga Islands) (faka Tonga)", "value": "to" },
        { "label": "Turkish (Türkçe)", "value": "tr" },
        { "label": "Tsonga (Xitsonga)", "value": "ts" },
        { "label": "Tatar (татар теле, tatar tele)", "value": "tt" },
        { "label": "Twi (Twi)", "value": "tw" },
        { "label": "Tahitian (Reo Tahiti)", "value": "ty" },
        { "label": "Uyghur (ئۇيغۇرچە‎, Uyghurche)", "value": "ug" },
        { "label": "Ukrainian (Українська)", "value": "uk" },
        { "label": "Urdu (اردو)", "value": "ur" },
        { "label": "Uzbek (Oʻzbek, Ўзбек, أۇزبېك‎)", "value": "uz" },
        { "label": "Venda (Tshivenḓa)", "value": "ve" },
        { "label": "Vietnamese (Tiếng Việt)", "value": "vi" },
        { "label": "Volapük (Volapük)", "value": "vo" },
        { "label": "Walloon (walon)", "value": "wa" },
        { "label": "Welsh (Cymraeg)", "value": "cy" },
        { "label": "Wolof (Wollof)", "value": "wo" },
        { "label": "Western Frisian (Frysk)", "value": "fy" },
        { "label": "Xhosa (isiXhosa)", "value": "xh" },
        { "label": "Yiddish (ייִדיש)", "value": "yi" },
        { "label": "Yoruba (Yorùbá)", "value": "yo" },
        { "label": "Zhuang, Chuang (Saɯ cueŋƅ, Saw cuengh)", "value": "za" },
        { "label": "Zulu (isiZulu)", "value": "zu" }
    ]
}